name: Deploy backend to EC2

on:
  push:
    barnches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Test docker build Ci test
      - name: Build Docker image ci test
        run: |
          docker build -t node-app .

      # Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            APP_DIR=~/todo_app

            echo "ğŸ” Checking if applcation exists..."

            if [ -d "$APP_DIR" ]; then 
              echo "ğŸŸ¢ App directory exists, updating applcation..."

              cd $APP_DIR/backend

              echo "ğŸ§² Pulling lasted code in backend..."
              git fetch origin production
              git reset --hard origin/production

              echo "ğŸŸ¢ Updating .env from github secrets..."
              if [ -f ".env" ]; then
                cp .env .env.backup_$(date +%s)
              fi
              echo "${{ secrets.BACKEND_ENV_FILE }}" > .env

              echo "ğŸš€ Rebuilding and restarting applcation..."
              cd ../frontend
              docker compose up --build -d

              echo "ğŸ§¹ Cleaning up unused images"
              docker image prune -f 

              echo "âœ… Backend update complete. ğŸ‰"
            else
              echo "ğŸŸ¨ App not found, Please start cicd pipeline from frontend first and then trigger backend pipeline"
            fi